//! Asserts the Rust encoders byte for byte against CosmJS.
//!
//! Per [ADR-0004](../../../docs/adr/0004-cosmos-client-libs.md), CosmJS is the reference
//! implementation. `tests/vectors/cosmos-signing.json` is generated by
//! `tests/vectors/generate/generate.mjs` and committed, so this test runs offline and a
//! reference change shows up as a reviewable diff.
//!
//! # Why byte equality and not round-tripping
//!
//! A round-trip test proves the code is self-consistent, which is exactly the property a
//! wrong-but-consistent encoder also has. Cosmos signs bytes, so the only test that means
//! anything is whether our bytes equal the reference bytes. A one-byte difference in
//! `auth_info`, an omitted `"memo":""`, or a missing default-value omission all produce a
//! signature that verifies against nothing, and the on-chain error says "unauthorized" with no
//! hint that the encoding was at fault.
//!
//! A failure here blocks release.

use std::path::{Path, PathBuf};

use serde_json::Value;
use zunia_cosmos::amount::Coin;
use zunia_cosmos::msg::{Height, Msg, VoteOption};
use zunia_cosmos::proto;
use zunia_cosmos::tx::{Fee, SignMode, SignerData, UnsignedTx};
use zunia_cosmos::{adr36_sign_bytes, amino};
use zunia_kernel::{Account, AddressScheme, Curve, DerivationPath, ExtendedKey, ZuniaMnemonic};

fn vectors_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/vectors/cosmos-signing.json")
}

fn load() -> Value {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "tests/vectors/cosmos-signing.json is missing; run \
         `cd tests/vectors/generate && pnpm install && pnpm generate`",
    );
    serde_json::from_str(&text).expect("vector file is not valid JSON")
}

fn str_at(value: &Value, path: &[&str]) -> String {
    let mut cursor = value;
    for key in path {
        cursor = &cursor[*key];
    }
    cursor
        .as_str()
        .unwrap_or_else(|| panic!("expected a string at {path:?}, got {cursor}"))
        .to_owned()
}

/// Rebuilds each vector's message from the same inputs the generator used.
///
/// Deliberately constructed rather than decoded from the vector: decoding our own encoder's
/// output and re-encoding it would test nothing. The inputs are duplicated here on purpose, so
/// that a change to the generator's inputs without a corresponding change here shows up as a
/// failure rather than passing silently.
fn message_for(name: &str, addresses: &Value) -> Msg {
    let from = str_at(addresses, &["cosmos"]);
    let valoper = str_at(addresses, &["cosmosvaloper"]);
    let safro = str_at(addresses, &["addr_safro"]);
    let to = "cosmos1jrkmdcwgq94uaamx6zax2luewlhf7u4kucx3kz".to_owned();

    match name {
        "msg_send" => Msg::Send {
            from_address: from,
            to_address: to,
            amount: vec![Coin::new("uatom", "1000000").unwrap()],
        },
        "msg_send_with_memo" => Msg::Send {
            from_address: from,
            to_address: to,
            amount: vec![Coin::new("uatom", "1").unwrap()],
        },
        "msg_delegate" => Msg::Delegate {
            delegator_address: from,
            validator_address: valoper,
            amount: Coin::new("uatom", "5000000").unwrap(),
        },
        "msg_undelegate" => Msg::Undelegate {
            delegator_address: from,
            validator_address: valoper,
            amount: Coin::new("uatom", "1000000").unwrap(),
        },
        "msg_begin_redelegate" => Msg::BeginRedelegate {
            delegator_address: from,
            validator_src_address: valoper.clone(),
            validator_dst_address: valoper,
            amount: Coin::new("uatom", "1000000").unwrap(),
        },
        "msg_withdraw_delegator_reward" => Msg::WithdrawDelegatorReward {
            delegator_address: from,
            validator_address: valoper,
        },
        "msg_vote" => Msg::Vote {
            proposal_id: 848,
            voter: from,
            option: VoteOption::NoWithVeto,
        },
        "msg_transfer_no_timeout" => Msg::IbcTransfer {
            source_port: "transfer".to_owned(),
            source_channel: "channel-141".to_owned(),
            token: Coin::new("uatom", "1000000").unwrap(),
            sender: from,
            receiver: safro,
            timeout_height: Height::default(),
            timeout_timestamp: 0,
            memo: String::new(),
        },
        "msg_transfer_with_timeout" => Msg::IbcTransfer {
            source_port: "transfer".to_owned(),
            source_channel: "channel-141".to_owned(),
            token: Coin::new("uatom", "1000000").unwrap(),
            sender: from,
            receiver: safro,
            timeout_height: Height {
                revision_number: 1,
                revision_height: 20_000_000,
            },
            timeout_timestamp: 1_700_000_000_000_000_000,
            memo: "forward".to_owned(),
        },
        "msg_execute_contract" => Msg::ExecuteContract {
            sender: from,
            contract: to,
            msg: br#"{"swap":{"offer":"100"}}"#.to_vec(),
            funds: vec![Coin::new("uatom", "100").unwrap()],
        },
        other => panic!(
            "vector \"{other}\" has no Rust counterpart; add it to message_for or remove it \
             from the generator"
        ),
    }
}

fn signer_from(vectors: &Value, public_key: Vec<u8>) -> SignerData {
    SignerData {
        chain_id: str_at(vectors, &["signer", "chain_id"]),
        account_number: vectors["signer"]["account_number"].as_u64().unwrap(),
        sequence: vectors["signer"]["sequence"].as_u64().unwrap(),
        public_key,
        eth_key_type: false,
    }
}

fn account() -> Account {
    let vectors = load();
    let mnemonic = ZuniaMnemonic::parse(&str_at(&vectors, &["key", "mnemonic"])).unwrap();
    let seed = mnemonic.to_seed("");
    Account::derive(
        seed.expose(),
        Curve::Secp256k1,
        DerivationPath::parse(&str_at(&vectors, &["key", "hd_path"])).unwrap(),
        AddressScheme::Cosmos,
        "cosmos",
    )
    .unwrap()
}

#[test]
fn key_derivation_matches_cosmjs() {
    let vectors = load();
    let mnemonic = ZuniaMnemonic::parse(&str_at(&vectors, &["key", "mnemonic"])).unwrap();
    let seed = mnemonic.to_seed("");
    assert_eq!(
        hex::encode(seed.expose()),
        str_at(&vectors, &["key", "seed_hex"]),
        "BIP-39 seed diverged"
    );

    let path = DerivationPath::parse(&str_at(&vectors, &["key", "hd_path"])).unwrap();
    let key = ExtendedKey::from_seed_and_path(Curve::Secp256k1, seed.expose(), &path).unwrap();
    assert_eq!(
        hex::encode(key.private_key().expose()),
        str_at(&vectors, &["key", "privkey_hex"]),
        "BIP-32 private key diverged"
    );
    assert_eq!(
        hex::encode(key.chain_code().expose()),
        str_at(&vectors, &["key", "chain_code_hex"]),
        "BIP-32 chain code diverged"
    );
    assert_eq!(
        hex::encode(key.public_key_bytes().unwrap()),
        str_at(&vectors, &["key", "pubkey_compressed_hex"]),
        "public key diverged"
    );
}

#[test]
fn addresses_match_cosmjs() {
    let vectors = load();
    let account = account();
    let id = account.account_id().unwrap();

    for prefix in ["cosmos", "cosmosvaloper", "addr_safro", "osmo"] {
        assert_eq!(
            id.to_bech32(prefix).unwrap(),
            str_at(&vectors, &["key", "addresses", prefix]),
            "{prefix} address diverged"
        );
    }
}

#[test]
fn direct_message_encoding_matches_cosmjs() {
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);

        assert_eq!(
            msg.type_url(),
            str_at(case, &["type_url"]),
            "{name}: type URL diverged"
        );
        assert_eq!(
            msg.amino_type(),
            str_at(case, &["amino_type"]),
            "{name}: Amino registry name diverged"
        );
        assert_eq!(
            hex::encode(msg.encode_proto()),
            str_at(case, &["direct", "msg_proto_hex"]),
            "{name}: protobuf message encoding diverged from CosmJS"
        );
    }
}

#[test]
fn direct_sign_bytes_match_cosmjs() {
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let account = account();
    let signer = signer_from(&vectors, account.public_key().unwrap());
    let fee = Fee::new(vec![Coin::new("uatom", "5000").unwrap()], 200_000).unwrap();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);
        let memo = str_at(case, &["memo"]);
        let tx = UnsignedTx::new(vec![msg], fee.clone(), memo).unwrap();

        assert_eq!(
            hex::encode(tx.encode_body()),
            str_at(case, &["direct", "body_bytes_hex"]),
            "{name}: TxBody diverged"
        );
        assert_eq!(
            hex::encode(tx.encode_auth_info(&signer, SignMode::Direct)),
            str_at(case, &["direct", "auth_info_bytes_hex"]),
            "{name}: AuthInfo diverged"
        );
        assert_eq!(
            hex::encode(tx.direct_sign_bytes(&signer).unwrap()),
            str_at(case, &["direct", "sign_bytes_hex"]),
            "{name}: SignDoc diverged, Direct signatures would be invalid"
        );
    }
}

#[test]
fn amino_sign_bytes_match_cosmjs() {
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let account = account();
    let signer = signer_from(&vectors, account.public_key().unwrap());
    let fee = Fee::new(vec![Coin::new("uatom", "5000").unwrap()], 200_000).unwrap();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);
        let memo = str_at(case, &["memo"]);
        let tx = UnsignedTx::new(vec![msg], fee.clone(), memo).unwrap();

        let doc = tx.amino_sign_doc(&signer).unwrap();
        assert_eq!(
            amino::to_canonical_string(&doc),
            str_at(case, &["amino", "sign_doc"]),
            "{name}: Amino sign document diverged"
        );
        assert_eq!(
            hex::encode(tx.amino_sign_bytes(&signer).unwrap()),
            str_at(case, &["amino", "sign_bytes_hex"]),
            "{name}: Amino sign bytes diverged, Amino signatures would be invalid"
        );
    }
}

#[test]
fn adr36_sign_bytes_match_cosmjs() {
    let vectors = load();
    let signer_address = str_at(&vectors, &["key", "addresses", "cosmos"]);

    for case in vectors["adr36"].as_array().unwrap() {
        let message = str_at(case, &["message"]);
        let bytes = adr36_sign_bytes(&signer_address, message.as_bytes());

        assert_eq!(
            String::from_utf8(bytes.clone()).unwrap(),
            str_at(case, &["sign_doc"]),
            "ADR-36 document diverged for {message:?}"
        );
        assert_eq!(
            hex::encode(&bytes),
            str_at(case, &["sign_bytes_hex"]),
            "ADR-36 sign bytes diverged for {message:?}"
        );
    }
}

#[test]
fn every_vector_has_a_rust_counterpart() {
    // Guards against a generator case that nothing asserts. Without this, adding a message to
    // the generator and forgetting the Rust side would leave it untested but look covered.
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let names: Vec<String> = vectors["cases"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| str_at(c, &["name"]))
        .collect();

    assert!(names.len() >= 10, "expected the full vector set");
    for name in &names {
        // Panics with a clear message if a case has no counterpart.
        let _ = message_for(name, addresses);
    }
}

#[test]
fn decoding_a_golden_sign_doc_produces_the_right_summary() {
    // The goldens come from CosmJS, so this exercises the decoder against bytes the Rust side
    // did not produce, which is the situation that matters: a dApp handing over Direct bytes.
    let vectors = load();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let bytes = hex::decode(str_at(case, &["direct", "sign_bytes_hex"])).unwrap();
        let decoded = zunia_cosmos::decode_direct_sign_doc(&bytes).unwrap();

        assert!(
            !decoded.has_unknown_msgs,
            "{name}: a supported message decoded as unknown, so the signing prompt would \
             show an alarming placeholder for a legitimate transaction"
        );
        assert_eq!(decoded.chain_id, str_at(&vectors, &["signer", "chain_id"]));
        assert_eq!(decoded.memo, str_at(case, &["memo"]));
        assert_eq!(decoded.gas_limit, 200_000);
        assert_eq!(decoded.sequence, 7);
        assert_eq!(decoded.account_number, 12345);
        assert_eq!(decoded.msgs.len(), 1);
        assert!(
            !decoded.summaries()[0].is_empty(),
            "{name}: no summary to show the user"
        );
    }
}

#[test]
fn signatures_over_golden_bytes_verify() {
    use sha2::{Digest, Sha256};

    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let account = account();
    let signer = signer_from(&vectors, account.public_key().unwrap());
    let fee = Fee::new(vec![Coin::new("uatom", "5000").unwrap()], 200_000).unwrap();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);
        let tx = UnsignedTx::new(vec![msg], fee.clone(), str_at(case, &["memo"])).unwrap();

        for (mode, key) in [
            (SignMode::Direct, "direct"),
            (SignMode::LegacyAminoJson, "amino"),
        ] {
            let golden = hex::decode(str_at(case, &[key, "sign_bytes_hex"])).unwrap();
            let signature = account.sign_cosmos(&golden).unwrap();
            let digest: [u8; 32] = Sha256::digest(&golden).into();
            assert!(
                zunia_kernel::verify_digest_secp256k1(
                    &account.public_key().unwrap(),
                    &digest,
                    signature.as_bytes()
                )
                .unwrap(),
                "{name}: signature over the CosmJS golden bytes did not verify in {mode:?}"
            );

            // And the broadcastable transaction must embed those exact bytes.
            let raw = tx.into_tx_raw(&signer, mode, signature.as_bytes()).unwrap();
            let fields = proto::decode_fields(&raw).unwrap();
            assert_eq!(
                proto::find_field(&fields, 3).unwrap().as_bytes().unwrap(),
                signature.as_bytes()
            );
        }
    }
}
