//! Asserts the Rust encoders byte for byte against CosmJS.
//!
//! Per [ADR-0004](../../../docs/adr/0004-cosmos-client-libs.md), CosmJS is the reference
//! implementation. `tests/vectors/cosmos-signing.json` is generated by
//! `tests/vectors/generate/generate.mjs` and committed, so this test runs offline and a
//! reference change shows up as a reviewable diff.
//!
//! # Why byte equality and not round-tripping
//!
//! A round-trip test proves the code is self-consistent, which is exactly the property a
//! wrong-but-consistent encoder also has. Cosmos signs bytes, so the only test that means
//! anything is whether our bytes equal the reference bytes. A one-byte difference in
//! `auth_info`, an omitted `"memo":""`, or a missing default-value omission all produce a
//! signature that verifies against nothing, and the on-chain error says "unauthorized" with no
//! hint that the encoding was at fault.
//!
//! A failure here blocks release.

use std::path::{Path, PathBuf};

use serde_json::Value;
use zunia_cosmos::amount::Coin;
use zunia_cosmos::msg::{Height, Msg, SwapAmountInRoute, SwapAmountInSplitRoute, VoteOption};
use zunia_cosmos::proto;
use zunia_cosmos::tx::{Fee, SignMode, SignerData, UnsignedTx};
use zunia_cosmos::{adr36_sign_bytes, amino};
use zunia_kernel::{Account, AddressScheme, Curve, DerivationPath, ExtendedKey, ZuniaMnemonic};

fn vectors_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/vectors/cosmos-signing.json")
}

fn load() -> Value {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "tests/vectors/cosmos-signing.json is missing; run \
         `cd tests/vectors/generate && pnpm install && pnpm generate`",
    );
    serde_json::from_str(&text).expect("vector file is not valid JSON")
}

fn str_at(value: &Value, path: &[&str]) -> String {
    let mut cursor = value;
    for key in path {
        cursor = &cursor[*key];
    }
    cursor
        .as_str()
        .unwrap_or_else(|| panic!("expected a string at {path:?}, got {cursor}"))
        .to_owned()
}

/// Rebuilds each vector's message from the same inputs the generator used.
///
/// Deliberately constructed rather than decoded from the vector: decoding our own encoder's
/// output and re-encoding it would test nothing. The inputs are duplicated here on purpose, so
/// that a change to the generator's inputs without a corresponding change here shows up as a
/// failure rather than passing silently.
fn message_for(name: &str, addresses: &Value) -> Msg {
    let from = str_at(addresses, &["cosmos"]);
    let valoper = str_at(addresses, &["cosmosvaloper"]);
    let safro = str_at(addresses, &["addr_safro"]);
    let osmo = str_at(addresses, &["osmo"]);
    let to = "cosmos1jrkmdcwgq94uaamx6zax2luewlhf7u4kucx3kz".to_owned();
    let hop = |pool_id: u64, token_out_denom: &str| SwapAmountInRoute {
        pool_id,
        token_out_denom: token_out_denom.to_owned(),
    };

    match name {
        "msg_send" => Msg::Send {
            from_address: from,
            to_address: to,
            amount: vec![Coin::new("uatom", "1000000").unwrap()],
        },
        "msg_send_with_memo" => Msg::Send {
            from_address: from,
            to_address: to,
            amount: vec![Coin::new("uatom", "1").unwrap()],
        },
        "msg_delegate" => Msg::Delegate {
            delegator_address: from,
            validator_address: valoper,
            amount: Coin::new("uatom", "5000000").unwrap(),
        },
        "msg_undelegate" => Msg::Undelegate {
            delegator_address: from,
            validator_address: valoper,
            amount: Coin::new("uatom", "1000000").unwrap(),
        },
        "msg_begin_redelegate" => Msg::BeginRedelegate {
            delegator_address: from,
            validator_src_address: valoper.clone(),
            validator_dst_address: valoper,
            amount: Coin::new("uatom", "1000000").unwrap(),
        },
        "msg_withdraw_delegator_reward" => Msg::WithdrawDelegatorReward {
            delegator_address: from,
            validator_address: valoper,
        },
        "msg_vote" => Msg::Vote {
            proposal_id: 848,
            voter: from,
            option: VoteOption::NoWithVeto,
        },
        "msg_transfer_no_timeout" => Msg::IbcTransfer {
            source_port: "transfer".to_owned(),
            source_channel: "channel-141".to_owned(),
            token: Coin::new("uatom", "1000000").unwrap(),
            sender: from,
            receiver: safro,
            timeout_height: Height::default(),
            timeout_timestamp: 0,
            memo: String::new(),
        },
        "msg_transfer_with_timeout" => Msg::IbcTransfer {
            source_port: "transfer".to_owned(),
            source_channel: "channel-141".to_owned(),
            token: Coin::new("uatom", "1000000").unwrap(),
            sender: from,
            receiver: safro,
            timeout_height: Height {
                revision_number: 1,
                revision_height: 20_000_000,
            },
            timeout_timestamp: 1_700_000_000_000_000_000,
            memo: "forward".to_owned(),
        },
        "msg_execute_contract" => Msg::ExecuteContract {
            sender: from,
            contract: to,
            msg: br#"{"swap":{"offer":"100"}}"#.to_vec(),
            funds: vec![Coin::new("uatom", "100").unwrap()],
        },
        "msg_swap_exact_amount_in" => Msg::SwapExactAmountIn {
            sender: osmo,
            routes: vec![hop(3586, SWAP_OUT_DENOM)],
            token_in: Coin::new("uosmo", "9950000").unwrap(),
            token_out_min_amount: "350000".to_owned(),
        },
        "msg_swap_exact_amount_in_multi_hop" => Msg::SwapExactAmountIn {
            sender: osmo,
            routes: vec![hop(1, ATOM_ON_OSMOSIS), hop(3586, SWAP_OUT_DENOM)],
            token_in: Coin::new("uosmo", "10000000").unwrap(),
            token_out_min_amount: "340000".to_owned(),
        },
        "msg_split_route_swap_exact_amount_in" => Msg::SplitRouteSwapExactAmountIn {
            sender: osmo,
            routes: vec![
                SwapAmountInSplitRoute {
                    pools: vec![hop(3498, SWAP_OUT_DENOM)],
                    token_in_amount: "6000000".to_owned(),
                },
                SwapAmountInSplitRoute {
                    pools: vec![hop(3586, SWAP_OUT_DENOM)],
                    token_in_amount: "4000000".to_owned(),
                },
            ],
            token_in_denom: "uosmo".to_owned(),
            token_out_min_amount: "350000".to_owned(),
        },
        // The memo is the case's, "rent & food <3>": the message is msg_send_with_memo's.
        "msg_send_memo_html" => Msg::Send {
            from_address: from,
            to_address: to,
            amount: vec![Coin::new("uatom", "1").unwrap()],
        },
        "msg_send_to_32_byte" => Msg::Send {
            from_address: from,
            to_address: TO_32_BYTE.to_owned(),
            amount: vec![Coin::new("uatom", "1000000").unwrap()],
        },
        "msg_execute_contract_32_no_funds" => Msg::ExecuteContract {
            sender: osmo,
            contract: XCS.to_owned(),
            msg: br#"{"recover":{}}"#.to_vec(),
            funds: vec![],
        },
        // Byte for byte what JSON.stringify wrote: the & stays raw in the protobuf, and only the
        // Amino document escapes it.
        "msg_execute_contract_nft_html" => Msg::ExecuteContract {
            sender: osmo,
            contract: CW721.to_owned(),
            msg: format!(
                r#"{{"transfer_nft":{{"recipient":"{NFT_RECIPIENT}","token_id":"rock & roll"}}}}"#
            )
            .into_bytes(),
            funds: vec![],
        },
        "msg_transfer_timestamp_only" => Msg::IbcTransfer {
            source_port: "transfer".to_owned(),
            source_channel: "channel-141".to_owned(),
            token: Coin::new("uatom", "1000000").unwrap(),
            sender: from,
            receiver: osmo,
            timeout_height: Height::default(),
            timeout_timestamp: 1_791_400_000_000_000_000,
            memo: String::new(),
        },
        other => panic!(
            "vector \"{other}\" has no Rust counterpart; add it to message_for or remove it \
             from the generator"
        ),
    }
}

/// The Osmosis denoms the generator's swap cases use: ATOM over IBC, and the token both swap
/// pools hold.
const ATOM_ON_OSMOSIS: &str =
    "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2";
const SWAP_OUT_DENOM: &str = "ibc/794C7D7F3B857713878A3A1927251FA6AC1EEE520424C1F6FAFE9BA26D476138";

/// Osmosis crosschain-swaps, a real contract: 32 bytes, as wasmd derives every contract address.
const XCS: &str = "osmo1uwk8xc6q0s6t5qcpr6rht3sczu6du83xq8pwxjua0hfj5hzcnh3sqxwvxs";
/// The same 32 bytes under the hub's prefix, the generator's 32-byte recipient.
const TO_32_BYTE: &str = "cosmos1uwk8xc6q0s6t5qcpr6rht3sczu6du83xq8pwxjua0hfj5hzcnh3s4mk53k";
/// The generator's CW721 collection, 32 bytes, and the account its NFT goes to.
const CW721: &str = "osmo19vxk34pf2uqf8warhsgqswa5sqyxnm493lxr4808gyy2rjs5yajq0c4l8v";
const NFT_RECIPIENT: &str = "osmo1jrkmdcwgq94uaamx6zax2luewlhf7u4k5r4pqs";

/// The cases whose recipient or contract is 32 bytes. They must decode as named messages: before
/// 0.1.1 the decoder held them to the 20-byte account rule and called every one unknown.
const THIRTY_TWO_BYTE_CASES: [&str; 3] = [
    "msg_send_to_32_byte",
    "msg_execute_contract_32_no_funds",
    "msg_execute_contract_nft_html",
];

fn signer_from(vectors: &Value, public_key: Vec<u8>) -> SignerData {
    SignerData {
        chain_id: str_at(vectors, &["signer", "chain_id"]),
        account_number: vectors["signer"]["account_number"].as_u64().unwrap(),
        sequence: vectors["signer"]["sequence"].as_u64().unwrap(),
        public_key,
        eth_key_type: false,
        eth_pub_key_type_url: None,
    }
}

fn account() -> Account {
    let vectors = load();
    let mnemonic = ZuniaMnemonic::parse(&str_at(&vectors, &["key", "mnemonic"])).unwrap();
    let seed = mnemonic.to_seed("");
    Account::derive(
        seed.expose(),
        Curve::Secp256k1,
        DerivationPath::parse(&str_at(&vectors, &["key", "hd_path"])).unwrap(),
        AddressScheme::Cosmos,
        "cosmos",
    )
    .unwrap()
}

#[test]
fn key_derivation_matches_cosmjs() {
    let vectors = load();
    let mnemonic = ZuniaMnemonic::parse(&str_at(&vectors, &["key", "mnemonic"])).unwrap();
    let seed = mnemonic.to_seed("");
    assert_eq!(
        hex::encode(seed.expose()),
        str_at(&vectors, &["key", "seed_hex"]),
        "BIP-39 seed diverged"
    );

    let path = DerivationPath::parse(&str_at(&vectors, &["key", "hd_path"])).unwrap();
    let key = ExtendedKey::from_seed_and_path(Curve::Secp256k1, seed.expose(), &path).unwrap();
    assert_eq!(
        hex::encode(key.private_key().expose()),
        str_at(&vectors, &["key", "privkey_hex"]),
        "BIP-32 private key diverged"
    );
    assert_eq!(
        hex::encode(key.chain_code().expose()),
        str_at(&vectors, &["key", "chain_code_hex"]),
        "BIP-32 chain code diverged"
    );
    assert_eq!(
        hex::encode(key.public_key_bytes().unwrap()),
        str_at(&vectors, &["key", "pubkey_compressed_hex"]),
        "public key diverged"
    );
}

#[test]
fn addresses_match_cosmjs() {
    let vectors = load();
    let account = account();
    let id = account.account_id().unwrap();

    for prefix in ["cosmos", "cosmosvaloper", "addr_safro", "osmo"] {
        assert_eq!(
            id.to_bech32(prefix).unwrap(),
            str_at(&vectors, &["key", "addresses", prefix]),
            "{prefix} address diverged"
        );
    }
}

#[test]
fn direct_message_encoding_matches_cosmjs() {
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);

        assert_eq!(
            msg.type_url(),
            str_at(case, &["type_url"]),
            "{name}: type URL diverged"
        );
        assert_eq!(
            msg.amino_type(),
            str_at(case, &["amino_type"]),
            "{name}: Amino registry name diverged"
        );
        assert_eq!(
            hex::encode(msg.encode_proto()),
            str_at(case, &["direct", "msg_proto_hex"]),
            "{name}: protobuf message encoding diverged from CosmJS"
        );
    }
}

#[test]
fn direct_sign_bytes_match_cosmjs() {
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let account = account();
    let signer = signer_from(&vectors, account.public_key().unwrap());
    let fee = Fee::new(vec![Coin::new("uatom", "5000").unwrap()], 200_000).unwrap();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);
        let memo = str_at(case, &["memo"]);
        let tx = UnsignedTx::new(vec![msg], fee.clone(), memo).unwrap();

        assert_eq!(
            hex::encode(tx.encode_body()),
            str_at(case, &["direct", "body_bytes_hex"]),
            "{name}: TxBody diverged"
        );
        assert_eq!(
            hex::encode(tx.encode_auth_info(&signer, SignMode::Direct)),
            str_at(case, &["direct", "auth_info_bytes_hex"]),
            "{name}: AuthInfo diverged"
        );
        assert_eq!(
            hex::encode(tx.direct_sign_bytes(&signer).unwrap()),
            str_at(case, &["direct", "sign_bytes_hex"]),
            "{name}: SignDoc diverged, Direct signatures would be invalid"
        );
    }
}

#[test]
fn amino_sign_bytes_match_cosmjs() {
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let account = account();
    let signer = signer_from(&vectors, account.public_key().unwrap());
    let fee = Fee::new(vec![Coin::new("uatom", "5000").unwrap()], 200_000).unwrap();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);
        let memo = str_at(case, &["memo"]);
        let tx = UnsignedTx::new(vec![msg], fee.clone(), memo).unwrap();

        let doc = tx.amino_sign_doc(&signer).unwrap();
        assert_eq!(
            amino::to_canonical_string(&doc),
            str_at(case, &["amino", "sign_doc"]),
            "{name}: Amino sign document diverged"
        );
        assert_eq!(
            hex::encode(tx.amino_sign_bytes(&signer).unwrap()),
            str_at(case, &["amino", "sign_bytes_hex"]),
            "{name}: Amino sign bytes diverged, Amino signatures would be invalid"
        );
    }
}

#[test]
fn adr36_sign_bytes_match_cosmjs() {
    let vectors = load();
    let signer_address = str_at(&vectors, &["key", "addresses", "cosmos"]);

    for case in vectors["adr36"].as_array().unwrap() {
        let message = str_at(case, &["message"]);
        let bytes = adr36_sign_bytes(&signer_address, message.as_bytes());

        assert_eq!(
            String::from_utf8(bytes.clone()).unwrap(),
            str_at(case, &["sign_doc"]),
            "ADR-36 document diverged for {message:?}"
        );
        assert_eq!(
            hex::encode(&bytes),
            str_at(case, &["sign_bytes_hex"]),
            "ADR-36 sign bytes diverged for {message:?}"
        );
    }
}

#[test]
fn every_vector_has_a_rust_counterpart() {
    // Guards against a generator case that nothing asserts. Without this, adding a message to
    // the generator and forgetting the Rust side would leave it untested but look covered.
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let names: Vec<String> = vectors["cases"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| str_at(c, &["name"]))
        .collect();

    assert!(names.len() >= 18, "expected the full vector set");
    for name in &names {
        // Panics with a clear message if a case has no counterpart.
        let _ = message_for(name, addresses);
    }
}

fn case_named(vectors: &Value, name: &str) -> Value {
    vectors["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == Value::String(name.to_owned()))
        .unwrap_or_else(|| panic!("vector {name} is missing"))
        .clone()
}

#[test]
fn thirty_two_byte_recipients_and_contracts_decode_as_named_messages() {
    // A crosschain swap's recovery, an NFT transfer, a payment to a DAO treasury: every real
    // contract and every module account is 32 bytes. Held to the 20-byte account rule, each came
    // back unknown and was refused unless blind signing was on.
    let vectors = load();
    for name in THIRTY_TWO_BYTE_CASES {
        let case = case_named(&vectors, name);
        let bytes = hex::decode(str_at(&case, &["direct", "sign_bytes_hex"])).unwrap();
        let decoded = zunia_cosmos::decode_direct_sign_doc(&bytes).unwrap();
        assert!(
            decoded.is_safe_to_sign_without_blind_signing(),
            "{name}: decoded as {:?}",
            decoded.msgs
        );
        let (named, prefix) = match &decoded.msgs[0] {
            zunia_cosmos::DecodedMsg::Send { to, .. } => (to.as_str(), "cosmos"),
            zunia_cosmos::DecodedMsg::ExecuteContract { contract, .. } => {
                (contract.as_str(), "osmo")
            }
            other => panic!("{name}: decoded as {other:?}"),
        };
        assert!(
            zunia_kernel::decode_bech32(named).is_err()
                && zunia_kernel::validate_contract_address(named, prefix).is_ok(),
            "{name}: {named} is meant to be 32 bytes on {prefix}"
        );
    }
}

#[test]
fn html_characters_in_a_memo_or_a_contract_message_are_signed_escaped() {
    // The reference serializer escapes & < > the way Go's encoding/json does, which is how the
    // chain rebuilds the document. These two cases pin that the goldens carry the escapes, so
    // the Amino comparison above is a comparison against the chain's spelling.
    let vectors = load();
    let backslash = char::from(0x5c_u8);
    for (name, escaped) in [
        (
            "msg_send_memo_html",
            format!("rent {backslash}u0026 food {backslash}u003c3{backslash}u003e"),
        ),
        (
            "msg_execute_contract_nft_html",
            format!("rock {backslash}u0026 roll"),
        ),
    ] {
        let doc = str_at(&case_named(&vectors, name), &["amino", "sign_doc"]);
        assert!(doc.contains(&escaped), "{name}: {doc}");
        assert!(
            !doc.contains('&') && !doc.contains('<') && !doc.contains('>'),
            "{name}: {doc}"
        );
    }
}

#[test]
fn decoding_a_golden_sign_doc_produces_the_right_summary() {
    // The goldens come from CosmJS and osmojs, so this exercises the decoder against bytes the
    // Rust side did not produce, which is the situation that matters: a dApp handing over Direct
    // bytes. The Osmosis app's swaps arrive exactly this way.
    let vectors = load();
    let addresses = &vectors["key"]["addresses"];

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let bytes = hex::decode(str_at(case, &["direct", "sign_bytes_hex"])).unwrap();
        let decoded = zunia_cosmos::decode_direct_sign_doc(&bytes).unwrap();

        assert!(
            !decoded.has_unknown_msgs,
            "{name}: a supported message decoded as unknown, so the signing prompt would \
             show an alarming placeholder for a legitimate transaction"
        );
        assert_eq!(decoded.chain_id, str_at(&vectors, &["signer", "chain_id"]));
        assert_eq!(decoded.memo, str_at(case, &["memo"]));
        assert_eq!(decoded.gas_limit, 200_000);
        assert_eq!(decoded.sequence, 7);
        assert_eq!(decoded.account_number, 12345);
        assert_eq!(decoded.msgs.len(), 1);
        assert!(
            !decoded.summaries()[0].is_empty(),
            "{name}: no summary to show the user"
        );
        // And the prompt must read the same whoever built the transaction: the summary of the
        // reference bytes is the summary of the message the wallet would have built itself.
        assert_eq!(
            decoded.summaries()[0],
            message_for(&name, addresses).summary(),
            "{name}: the decoder describes the reference bytes differently from the builder"
        );
    }
}

#[test]
fn osmosis_swaps_built_by_osmojs_decode_into_named_swaps() {
    // The Osmosis app signs these through `signDirect`, so this is what the prompt shows for
    // them. Pinned word for word: the input, the floor on the output, the output denom and the
    // pools are what a user checks before approving, and none of them may be lost or reordered.
    let vectors = load();
    let expected = [
        (
            "msg_swap_exact_amount_in",
            format!("Swap 9950000 uosmo for at least 350000 {SWAP_OUT_DENOM} through pool 3586"),
        ),
        (
            "msg_swap_exact_amount_in_multi_hop",
            format!(
                "Swap 10000000 uosmo for at least 340000 {SWAP_OUT_DENOM} through pools 1 → 3586"
            ),
        ),
        (
            "msg_split_route_swap_exact_amount_in",
            format!(
                "Swap 10000000 uosmo for at least 350000 {SWAP_OUT_DENOM} through 2 routes \
                 (pools 3498; 3586)"
            ),
        ),
    ];

    for (name, summary) in expected {
        let case = vectors["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["name"] == Value::String(name.to_owned()))
            .unwrap_or_else(|| panic!("vector {name} is missing"));
        let bytes = hex::decode(str_at(case, &["direct", "sign_bytes_hex"])).unwrap();
        let decoded = zunia_cosmos::decode_direct_sign_doc(&bytes).unwrap();

        assert!(decoded.is_safe_to_sign_without_blind_signing(), "{name}");
        assert!(
            matches!(
                decoded.msgs[0],
                zunia_cosmos::DecodedMsg::SwapExactAmountIn { .. }
                    | zunia_cosmos::DecodedMsg::SplitRouteSwapExactAmountIn { .. }
            ),
            "{name}: decoded as {:?}",
            decoded.msgs[0]
        );
        assert_eq!(decoded.summaries()[0], summary, "{name}");
        assert_eq!(
            decoded.msgs[0].addresses(),
            vec![str_at(&vectors, &["key", "addresses", "osmo"])],
            "{name}: the sender is the only account a swap names"
        );
    }
}

#[test]
fn signatures_over_golden_bytes_verify() {
    use sha2::{Digest, Sha256};

    let vectors = load();
    let addresses = &vectors["key"]["addresses"];
    let account = account();
    let signer = signer_from(&vectors, account.public_key().unwrap());
    let fee = Fee::new(vec![Coin::new("uatom", "5000").unwrap()], 200_000).unwrap();

    for case in vectors["cases"].as_array().unwrap() {
        let name = str_at(case, &["name"]);
        let msg = message_for(&name, addresses);
        let tx = UnsignedTx::new(vec![msg], fee.clone(), str_at(case, &["memo"])).unwrap();

        for (mode, key) in [
            (SignMode::Direct, "direct"),
            (SignMode::LegacyAminoJson, "amino"),
        ] {
            let golden = hex::decode(str_at(case, &[key, "sign_bytes_hex"])).unwrap();
            let signature = account.sign_cosmos(&golden).unwrap();
            let digest: [u8; 32] = Sha256::digest(&golden).into();
            assert!(
                zunia_kernel::verify_digest_secp256k1(
                    &account.public_key().unwrap(),
                    &digest,
                    signature.as_bytes()
                )
                .unwrap(),
                "{name}: signature over the CosmJS golden bytes did not verify in {mode:?}"
            );

            // And the broadcastable transaction must embed those exact bytes.
            let raw = tx.into_tx_raw(&signer, mode, signature.as_bytes()).unwrap();
            let fields = proto::decode_fields(&raw).unwrap();
            assert_eq!(
                proto::find_field(&fields, 3).unwrap().as_bytes().unwrap(),
                signature.as_bytes()
            );
        }
    }
}
