//! Asserts kernel address derivation against CosmJS for every chain in the registry.
//!
//! `tests/vectors/registry-addresses.json` is generated by
//! `tests/vectors/generate/address-vectors.mjs` from the real `zunia-chain-registry`, one case
//! per distinct (coin type, prefix, address scheme) combination.
//!
//! # Why this exists separately from the BIP vectors
//!
//! The BIP vectors prove the derivation maths is right. They say nothing about whether Zunia
//! applies that maths with the parameters the registry supplies. Getting a coin type or an
//! address scheme wrong yields a perfectly valid address that belongs to nobody: funds sent
//! there are gone, and the failure is invisible until someone tries to spend. Every chain the
//! wallet offers is checked, not a sample.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde_json::Value;
use zunia_kernel::{
    convert_prefix, decode_bech32, validate_address, AccountId, AddressScheme, Curve,
    DerivationPath, ExtendedKey, ZuniaMnemonic,
};

fn vectors_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/vectors/registry-addresses.json")
}

fn load() -> Value {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "tests/vectors/registry-addresses.json is missing; run \
         `cd tests/vectors/generate && pnpm install && node address-vectors.mjs`",
    );
    serde_json::from_str(&text).expect("vector file is not valid JSON")
}

fn scheme_of(case: &Value) -> AddressScheme {
    match case["scheme"].as_str().unwrap() {
        "cosmos" => AddressScheme::Cosmos,
        "ethermint" => AddressScheme::Ethermint,
        other => panic!("unknown address scheme {other:?} in the vectors"),
    }
}

fn str_of(case: &Value, key: &str) -> String {
    case[key]
        .as_str()
        .unwrap_or_else(|| panic!("missing {key} in {case}"))
        .to_owned()
}

fn seed() -> zunia_kernel::SecretBytes {
    let vectors = load();
    ZuniaMnemonic::parse(vectors["mnemonic"].as_str().unwrap())
        .unwrap()
        .to_seed("")
}

#[test]
fn the_vector_set_actually_covers_the_registry() {
    // A generator change that quietly stopped emitting Ethermint chains, or dropped to a
    // handful of cases, would leave this file passing while testing almost nothing.
    let vectors = load();
    let cases = vectors["cases"].as_array().unwrap();

    assert_eq!(
        vectors["registry"]["chains_skipped"].as_u64().unwrap(),
        0,
        "some registry files were skipped; every chain must be derivable"
    );
    assert!(
        vectors["registry"]["chains_parsed"].as_u64().unwrap() >= 330,
        "the registry should have at least 330 chains"
    );
    assert!(
        cases.len() >= 200,
        "expected at least 200 distinct combinations"
    );

    let coin_types: BTreeSet<u64> = cases
        .iter()
        .map(|c| c["coin_type"].as_u64().unwrap())
        .collect();
    assert!(
        coin_types.len() >= 20,
        "expected at least 20 distinct coin types, got {}",
        coin_types.len()
    );
    assert!(coin_types.contains(&118), "coin type 118 must be present");
    assert!(coin_types.contains(&60), "coin type 60 must be present");

    let ethermint = cases.iter().filter(|c| c["scheme"] == "ethermint").count();
    assert!(
        ethermint >= 40,
        "expected at least 40 Ethermint combinations, got {ethermint}"
    );
}

#[test]
fn every_registry_chain_derives_the_address_cosmjs_derives() {
    let vectors = load();
    let seed = seed();

    for case in vectors["cases"].as_array().unwrap() {
        let chain_id = str_of(case, "chain_id");
        let prefix = str_of(case, "prefix");
        let coin_type = case["coin_type"].as_u64().unwrap() as u32;
        let scheme = scheme_of(case);

        let path = DerivationPath::bip44(coin_type, 0, 0);
        let key = ExtendedKey::from_seed_and_path(Curve::Secp256k1, seed.expose(), &path)
            .unwrap_or_else(|e| panic!("{chain_id}: derivation failed: {e}"));
        let public_key = key.public_key_bytes().unwrap();

        assert_eq!(
            hex::encode(&public_key),
            str_of(case, "pubkey_compressed_hex"),
            "{chain_id}: public key diverged for coin type {coin_type}"
        );

        let id = AccountId::from_public_key(scheme, &public_key)
            .unwrap_or_else(|e| panic!("{chain_id}: account id failed: {e}"));
        assert_eq!(
            hex::encode(id.as_bytes()),
            str_of(case, "account_id_hex"),
            "{chain_id}: account id diverged under {scheme:?}"
        );

        let address = id
            .to_bech32(&prefix)
            .unwrap_or_else(|e| panic!("{chain_id}: bech32 failed for prefix {prefix}: {e}"));
        assert_eq!(
            address,
            str_of(case, "address"),
            "{chain_id}: address diverged, funds sent here would be unrecoverable"
        );

        // The address the wallet shows must also pass the validator the wallet uses on input,
        // otherwise a user cannot paste their own address back in.
        validate_address(&address, &prefix)
            .unwrap_or_else(|e| panic!("{chain_id}: own address failed validation: {e}"));

        if let Some(valoper) = case["valoper_address"].as_str() {
            assert_eq!(
                id.to_bech32(&str_of(case, "valoper_prefix")).unwrap(),
                valoper,
                "{chain_id}: validator address diverged, so staking would target nothing"
            );
        }

        if let Some(eth) = case["eth_address"].as_str() {
            assert_eq!(
                id.to_eth_hex().to_lowercase(),
                eth.to_lowercase(),
                "{chain_id}: the 0x form of the same account diverged"
            );
        }
    }
}

#[test]
fn ethermint_and_cosmos_schemes_never_agree() {
    // If the scheme inference ever regressed to a no-op, every assertion above would still
    // pass for cosmos chains and fail loudly for Ethermint ones. This states the underlying
    // property directly: the two schemes hash the same key to different accounts, so picking
    // the wrong one is always wrong, never harmlessly wrong.
    let vectors = load();
    let seed = seed();
    let path = DerivationPath::bip44(60, 0, 0);
    let key = ExtendedKey::from_seed_and_path(Curve::Secp256k1, seed.expose(), &path).unwrap();
    let public_key = key.public_key_bytes().unwrap();

    let cosmos = AccountId::from_public_key(AddressScheme::Cosmos, &public_key).unwrap();
    let ethermint = AccountId::from_public_key(AddressScheme::Ethermint, &public_key).unwrap();
    assert_ne!(cosmos.as_bytes(), ethermint.as_bytes());

    // Every coin-type-60 chain currently in the registry does declare `eth-address-gen`, so
    // the vectors cannot demonstrate the converse. That case is covered by a fixture in
    // `zunia-registry` (`coin_type_60_alone_does_not_imply_ethermint`), because a chain using
    // coin type 60 purely for Ledger compatibility while keeping Cosmos addresses is legal and
    // has to keep working. What is asserted here is that the registry's Ethermint chains get
    // the Ethermint account and not the Cosmos one.
    let vectors_cases = vectors["cases"].as_array().unwrap();
    let coin60: Vec<&Value> = vectors_cases
        .iter()
        .filter(|c| c["coin_type"] == 60)
        .collect();
    assert!(
        !coin60.is_empty(),
        "coin type 60 must appear in the registry"
    );

    for case in coin60 {
        let expected = str_of(case, "account_id_hex");
        assert_eq!(
            expected,
            hex::encode(ethermint.as_bytes()),
            "{}: expected the Ethermint account for a coin-type-60 chain",
            str_of(case, "chain_id")
        );
        assert_ne!(
            expected,
            hex::encode(cosmos.as_bytes()),
            "{}: derived the Cosmos account, so its address belongs to nobody",
            str_of(case, "chain_id")
        );
    }
}

#[test]
fn prefix_conversion_preserves_the_account() {
    // The dashboard and the IBC screen both convert an address between prefixes. A conversion
    // that changed the payload would send an IBC transfer to a different account entirely.
    let vectors = load();
    let cosmos_cases: Vec<&Value> = vectors["cases"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|c| c["scheme"] == "cosmos")
        .collect();

    let source = cosmos_cases
        .iter()
        .find(|c| c["prefix"] == "cosmos")
        .expect("the cosmos prefix must be in the registry");
    let source_address = str_of(source, "address");
    let source_coin_type = source["coin_type"].as_u64().unwrap();

    let mut converted = 0;
    for case in &cosmos_cases {
        // Only chains sharing the coin type share the account, so only those can be compared.
        if case["coin_type"].as_u64().unwrap() != source_coin_type {
            continue;
        }
        let target_prefix = str_of(case, "prefix");
        let result = convert_prefix(&source_address, &target_prefix)
            .unwrap_or_else(|e| panic!("converting cosmos -> {target_prefix} failed: {e}"));
        assert_eq!(
            result,
            str_of(case, "address"),
            "cosmos -> {target_prefix} conversion produced the wrong address"
        );

        let decoded = decode_bech32(&result).unwrap();
        assert_eq!(decoded.prefix, target_prefix);
        assert_eq!(
            decoded.account.as_bytes(),
            decode_bech32(&source_address).unwrap().account.as_bytes(),
            "conversion changed the account payload"
        );
        converted += 1;
    }
    assert!(
        converted > 50,
        "expected to convert into many prefixes, did {converted}"
    );
}

#[test]
fn a_valid_address_for_one_chain_is_rejected_for_another() {
    // Sending to a correctly formed address on the wrong chain is a common and unrecoverable
    // mistake, so prefix checking has to be strict rather than advisory.
    let vectors = load();
    let cases = vectors["cases"].as_array().unwrap();

    let cosmos = cases.iter().find(|c| c["prefix"] == "cosmos").unwrap();
    let osmo = cases.iter().find(|c| c["prefix"] == "osmo").unwrap();

    let cosmos_address = str_of(cosmos, "address");
    assert!(validate_address(&cosmos_address, "cosmos").is_ok());
    assert!(
        validate_address(&cosmos_address, "osmo").is_err(),
        "a cosmos address must not validate as an osmo address"
    );
    assert!(validate_address(&str_of(osmo, "address"), "cosmos").is_err());

    // A tampered checksum must fail even with the right prefix.
    let mut tampered: Vec<char> = cosmos_address.chars().collect();
    let last = tampered.len() - 1;
    tampered[last] = if tampered[last] == 'q' { 'p' } else { 'q' };
    let tampered: String = tampered.into_iter().collect();
    assert!(
        validate_address(&tampered, "cosmos").is_err(),
        "a single flipped character must fail the checksum"
    );
}
