#!/usr/bin/env bash
# Cross-compiles crates/ffi for the Android and iOS targets that mobile CI pins, then
# assembles an xcframework. Artifacts land in dist/native/ and are attached to the GitHub
# Release by the release workflow; they are never published to a package registry.
#
# Requires: rustup, Android NDK (ANDROID_NDK_HOME), Xcode (on macOS, for iOS).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/dist/native"
mkdir -p "$OUT"

cd "$ROOT"

ANDROID_TARGETS=(
  aarch64-linux-android
  armv7-linux-androideabi
  x86_64-linux-android
)

IOS_TARGETS=(
  aarch64-apple-ios
  aarch64-apple-ios-sim
)

# Every zunia_* symbol the library exports must be declared in the shipped header. Dart binds
# by symbol name and so never notices a stale header, which is exactly how the five
# transaction entry points shipped in the library and stayed undeclared. C and Objective-C
# callers cannot see an undeclared symbol at all.
verify_header_covers_library() {
  local lib="$1" header="$2"
  local missing=()
  local symbol
  while read -r symbol; do
    [[ -z "$symbol" ]] && continue
    grep -q "\b${symbol}\b" "$header" || missing+=("$symbol")
  done < <(nm -gU "$lib" 2>/dev/null | awk '{print $NF}' |
    sed -n 's/^_\(zunia_[A-Za-z0-9_]*\)$/\1/p' | sort -u)

  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "zunia_ffi.h does not declare: ${missing[*]}" >&2
    echo "regenerate it from crates/ffi/src/lib.rs in this script" >&2
    return 1
  fi
  echo "header declares all ${lib##*/} zunia_* exports"
}

build_android() {
  if [[ -z "${ANDROID_NDK_HOME:-}" ]]; then
    echo "ANDROID_NDK_HOME unset; skipping Android targets" >&2
    return 0
  fi
  if ! command -v cargo-ndk >/dev/null 2>&1; then
    cargo install cargo-ndk --locked
  fi
  for target in "${ANDROID_TARGETS[@]}"; do
    rustup target add "$target"
  done
  cargo ndk \
    -t arm64-v8a -t armeabi-v7a -t x86_64 \
    -o "$OUT/android" \
    build -p zunia-ffi --release
  (cd "$OUT" && tar -czf android-libs.tar.gz android)
}

build_ios() {
  if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "not macOS; skipping iOS targets" >&2
    return 0
  fi
  if ! command -v xcodebuild >/dev/null 2>&1 ||
    ! xcrun --sdk iphoneos --show-sdk-path >/dev/null 2>&1; then
    echo "full Xcode with the iOS SDK not found; skipping iOS targets" >&2
    return 0
  fi
  for target in "${IOS_TARGETS[@]}"; do
    rustup target add "$target"
    cargo build -p zunia-ffi --release --target "$target"
  done

  local ios_lib sim_lib
  ios_lib="$ROOT/target/aarch64-apple-ios/release/libzunia_ffi.a"
  sim_lib="$ROOT/target/aarch64-apple-ios-sim/release/libzunia_ffi.a"
  mkdir -p "$OUT/ios/headers"
  cat > "$OUT/ios/headers/zunia_ffi.h" <<'EOF'
/*
 * Zunia wallet kernel, C ABI.
 *
 * Generated by scripts/build-native.sh. Do not edit by hand: the build verifies that every
 * zunia_* symbol the static library exports is declared here, and a hand-edit that drifts
 * from crates/ffi/src/lib.rs is how a caller ends up passing a 32-bit value to a parameter
 * the ABI says is 64-bit and signing for the wrong account.
 *
 * Every function returns a NUL-terminated, heap-allocated C string that the caller MUST
 * release with zunia_string_free. A string beginning with "error: " is a failure, and the
 * remainder is the message; there is no other error channel and no function panics. A NULL
 * return means allocation failed.
 *
 * Required pointer parameters must be non-NULL. `memo` and `passphrase` treat NULL as the
 * empty string. `eth_key_type` is a boolean: 0 or 1.
 *
 * This library holds decrypted key material in process memory while it runs. Call it only
 * from a trusted process.
 */
#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Releases any string returned by this library. Safe on NULL. */
void zunia_string_free(char *ptr);

char *zunia_kernel_version(void);
char *zunia_generate_mnemonic(uint32_t words);

char *zunia_seal_keyring(const char *phrase, const char *password, const char *metadata_json);
char *zunia_open_keyring(const char *envelope_json, const char *password);

char *zunia_derive_address(const char *phrase, const char *passphrase, const char *chain_json,
                           uint32_t account_index);
char *zunia_sign_cosmos(const char *phrase, const char *passphrase, const char *chain_json,
                        uint32_t account_index, const char *sign_bytes_hex);
char *zunia_decode_direct_tx(const char *sign_doc_hex);

/*
 * Deprecated: only expresses a bank send. Use zunia_build_sign_bytes with a
 * [{"typeUrl":"/cosmos.bank.v1beta1.MsgSend","value":{...}}] payload, which is the only path
 * that can also express staking, governance, IBC and contract calls.
 */
char *zunia_build_bank_send_direct(const char *chain_id, const char *from, const char *to,
                                   const char *amount, const char *denom, const char *memo,
                                   uint64_t account_number, uint64_t sequence,
                                   const char *fee_amount, const char *fee_denom,
                                   uint64_t gas_limit, const char *public_key_hex,
                                   uint8_t eth_key_type);

/*
 * The general transaction surface. `msgs_json` is a JSON array of
 * {"typeUrl": "...", "value": { ...proto-JSON, snake_case, amounts as strings... }} and
 * `fee_json` is {"amount":[{"denom":"...","amount":"..."}],"gas_limit":"200000"}.
 *
 * For /cosmwasm.wasm.v1.MsgExecuteContract, value.msg is a BASE64 string of the contract
 * JSON. `mode` is "direct" or "amino".
 */

/* Hex sign bytes. Pure: no key material crosses this call. */
char *zunia_build_sign_bytes(const char *chain_id, const char *msgs_json, const char *fee_json,
                             const char *memo, uint64_t account_number, uint64_t sequence,
                             const char *public_key_hex, uint8_t eth_key_type,
                             const char *mode);

/*
 * Hex TxRaw for a signature made over zunia_build_sign_bytes' output with the same
 * arguments. The signature is not verified here and cannot be: one made over different
 * bytes assembles cleanly and fails on chain as an opaque "unauthorized".
 */
char *zunia_assemble_tx_raw(const char *chain_id, const char *msgs_json, const char *fee_json,
                            const char *memo, uint64_t account_number, uint64_t sequence,
                            const char *public_key_hex, uint8_t eth_key_type, const char *mode,
                            const char *signature_hex);

/* Hex TxRaw with a 64-byte zero signature, for POST /cosmos/tx/v1beta1/simulate. */
char *zunia_build_simulate_tx(const char *chain_id, const char *msgs_json,
                              const char *fee_json, const char *memo, uint64_t account_number,
                              uint64_t sequence, const char *public_key_hex,
                              uint8_t eth_key_type);

/*
 * derive -> sign bytes -> sign -> assemble. Returns a hex TxRaw. Holds the mnemonic and
 * zeroizes it. The only entry point given a chain document, so it also refuses a chain_id
 * that disagrees with it and addresses carrying another chain's bech32 prefix.
 */
char *zunia_sign_tx(const char *phrase, const char *passphrase, const char *chain_json,
                    uint32_t account_index, const char *chain_id, const char *msgs_json,
                    const char *fee_json, const char *memo, uint64_t account_number,
                    uint64_t sequence, const char *mode);

/* JSON describing what would be signed, without signing it. Pure. gasLimit is a string. */
char *zunia_preview_tx(const char *chain_id, const char *msgs_json, const char *fee_json,
                       const char *memo, uint64_t account_number, uint64_t sequence,
                       const char *public_key_hex, uint8_t eth_key_type, const char *mode);

#ifdef __cplusplus
}
#endif
EOF

  verify_header_covers_library "$ios_lib" "$OUT/ios/headers/zunia_ffi.h"

  rm -rf "$OUT/ZuniaCore.xcframework"
  xcodebuild -create-xcframework \
    -library "$ios_lib" -headers "$OUT/ios/headers" \
    -library "$sim_lib" -headers "$OUT/ios/headers" \
    -output "$OUT/ZuniaCore.xcframework"

  (cd "$OUT" && tar -czf ZuniaCore.xcframework.tar.gz ZuniaCore.xcframework)
}

echo "building Android"
build_android
echo "building iOS"
build_ios

# Checksums for the release notes. Consumers verify these before loading a native lib.
if compgen -G "$OUT/*.tar.gz" >/dev/null; then
  (cd "$OUT" && shasum -a 256 ./*.tar.gz > SHA256SUMS)
else
  rm -f "$OUT/SHA256SUMS"
  echo "no artifacts were produced; both Android and iOS were skipped" >&2
fi
ls -la "$OUT"
